# use the shared YaST defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop-1.24.1_yast_style.yml

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/BlockLength:
  Max: 86
  Exclude:
    - "test/**/*"

# this needs more testing if we can have frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false

